DROP TABLE MVCBOARD;

CREATE TABLE MVCBOARD(
	SEQ INT AUTO_UNCREMENT PRIMARY KEY,
	WRITER VARCHAR(30) NOT NULL,
	TITLE VARCHAR(1000) NOT NULL,
	CONTENT VARCHAR(2000) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO MVCBOARD VALUES(NULL,'관리자','테스트중','테스트1234 ABCD',NOW());

SELECT * FROM MVCBOARD;