CREATE TABLE BOARD (
	BOARD_NO INT AUTO_INCREMENT PRIMARY KEY COMMENT '글번호',
	BOARD_TITLE VARCHAR(100) NOT NULL COMMENT '제목',
	BOARD_WRITER VARCHAR(100) NOT NULL COMMENT '작성자',
	BOARD_CONTENT VARCHAR(500) NOT NULL COMMENT '내용',
	BOARD_DATE DATE NOT NULL COMMENT '날짜'
);
DROP TABLE BOARD;
SELECT * FROM BOARD;

SHOW FULL COLUMNS FROM BOARD;

-- INSERT INTO BOARD VALUES(NULL,'a','123','3456','190402');
