DROP TABLE MYBOARD;

CREATE TABLE MYBOARD(
	MYNO INT AUTO_INCREMENT PRIMARY KEY,
	MYNAME VARCHAR(500) NOT NULL,
	MYTITLE VARCHAR(1000) NOT NULL,
	MYCONTENT VARCHAR(4000) NOT NULL,
	MYDATE DATE NOT NULL
);

INSERT INTO MYBOARD VALUES(NULL,'관리자','스프링','SPRING MVC 재밌다',NOW());

SELECT * FROM MYBOARD ORDER BY MYNO DESC;
