DROP TABLE MYMEMBER;
CREATE TABLE MYMEMBER(
	MYNO INT AUTO_INCREMENT PRIMARY KEY,
	MYID VARCHAR(100) NOT NULL UNIQUE,
	MYPW VARCHAR(100) NOT NULL,
	MYNAME VARCHAR(50) NOT NULL,
	MYADDR VARCHAR(1000) NOT NULL,
	MYPHONE VARCHAR(500) NOT NULL UNIQUE,
	MYEMAIL VARCHAR(300) NOT NULL UNIQUE,
	MYENABLED VARCHAR(2) NOT NULL CHECK(MYENABLED IN ('Y','N')),
	MYROLE VARCHAR(50) NOT NULL
)
-- 멤버번호, 아이디, 비번, 이름, 주소, 전화번호, 이메일, 가입(탈퇴)여부, 등급(ADMIN,USER,MANAGER...)


SELECT * FROM MYMEMBER;


INSERT INTO MYMEMBER VALUES(NULL,'ADMIN','ADMIN123','관리자','관리시 관리구 관리동','010-5555-5555','ADMING@MYMEMBER.COM','Y','ADMIN')