DROP TABLE MYBOARD;

CREATE TABLE MYBOARD(
	MYNO INT AUTO_INCREMENT PRIMARY KEY,
	MYNAME VARCHAR(500) NOT NULL,
	MYTITLE VARCHAR(1000) NOT NULL,
	MYCONTENT VARCHAR(4000) NOT NULL,
	MYDATE DATE NOT NULL
);

INSERT INTO MYBOARD VALUES(NULL,'관리자','스프링','SPRING MVC 재밌다',NOW());

SELECT * FROM MYBOARD ORDER BY MYNO DESC;

-------------------------------------
DROP TABLE MYMEMBER;


CREATE TABLE MYMEMBER(
	MEMBRNO INT AUTO_INCREMENT PRIMARY KEY,
	MEMBRID VARCHAR(500) NOT NULL UNIQUE,
	MEMBRPW VARCHAR(1000) NOT NULL,
	MEMBRNAME VARCHAR(1000) NOT NULL
);

INSERT INTO MYMEMBER VALUES(NULL,'ADMIN','1234','관리자');

SELECT * FROM MYMEMBER;